services:
  streambot:
    image: quay.io/ydrag0n/streambot:latest
    container_name: streambot
    restart: always
    env_file:
      - .env
    volumes:
      - ./videos:/home/bots/StreamBot/videos
    ports:
      - 3000:3000
